### ISSUE TITLE
Next.md needs written

### ISSUE THREAD

**Issue by patrickpierson** [hackfrederick/hackathon2016#1]
The next.md needs to be written so that the weather to nexmo logic works and pushes information to a phone.

I'll write up the code for doing that.

**Comment by mblayman** [comment]
As I mentioned in the email thread, /next/ is intended to be the ideas page for attendees after they've completed the /connecting/ page which wires weather and Nexmo together.

I agree /next/ needs to be written, but the subject is different. 😄 

Some ideas:
- Point to documentation about `raw_input` so people can learn how to make the script interactive and search for the location of their choosing.
- Tell them to turn off networking so they can watch the script fail, then teach them a bit about error handling.
- Use other weather or Nexmo APIs
- Use Django + ngrok.com to provide a webhook URL for Nexmo to play with webhooks.

**Comment by patrickpierson** [comment]
Got it! Let me see what I can come up with this week.
